name: mobx_example
description: MobX example project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.0
  http: ^0.13.3
  mobx: ^2.0.0
  mobx_codegen: ^2.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true